version: '3.8'

services:
  # CPU development environment
  dev-cpu:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile
      target: cpu-dev
    volumes:
      - ../../:/app
    ports:
      - "8000:8000"  # For any web interfaces
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=DEBUG
    command: python -m src.ai_platform_trainer.utils.environment

  # GPU development environment (requires nvidia-docker)
  dev-gpu:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile
      target: gpu-dev
    volumes:
      - ../../:/app
    ports:
      - "8001:8000"  # For any web interfaces
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=DEBUG
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: python -m src.ai_platform_trainer.utils.environment

  # Production environment
  prod:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile
      target: production
    ports:
      - "8080:8080"  # For any web interfaces
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
