name: ai-platform-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=23.0.0
  - numpy>=1.19.0
  - pygame>=2.1.0
  - cudatoolkit=11.8
  - pytorch>=1.9.0
  - pytorch-cuda=11.8
  - pip:
    - noise>=1.2.2
    - gymnasium>=0.28.0
    - stable-baselines3>=1.6.0
    - black>=23.1.0
    - isort>=5.12.0
    - flake8>=6.0.0
    - mypy>=1.0.0
    - pytest>=7.0.0
    - pytest-cov>=4.0.0
    - pre-commit>=3.0.0
