name: Azure Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Full history for proper versioning
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run tests
      run: |
        pytest -v tests/
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and deploy to Azure Container Apps
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # Build the container image
          az acr build --registry aiPlatformRegistry --image ai-platform-trainer:${{ github.sha }} .
          
          # Update the container app with the new image
          az containerapp update \
            --resource-group ai-platform-rg \
            --name ai-platform-trainer-app \
            --image aiPlatformRegistry.azurecr.io/ai-platform-trainer:${{ github.sha }}

  setup-gpu:
    name: Setup GPU Environment
    runs-on: ubuntu-latest
    needs: deploy
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Create Azure ML Workspace
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # Create ML workspace if it doesn't exist
          az ml workspace create \
            --resource-group ai-platform-rg \
            --name ai-platform-ml-workspace \
            --location eastus
          
          # Create compute cluster with GPU support
          az ml computetarget create amlcompute \
            --name gpu-cluster \
            --vm-size Standard_NC6 \
            --resource-group ai-platform-rg \
            --workspace-name ai-platform-ml-workspace \
            --min-nodes 0 \
            --max-nodes 4 \
            --idle-seconds-before-scaledown 600
    
    - name: Upload training data
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # Upload data to datastore
          az ml datastore upload \
            --name workspaceblobstore \
            --src-path data/raw \
            --target-path training-data \
            --resource-group ai-platform-rg \
            --workspace-name ai-platform-ml-workspace
