name: Build Mac App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3

      # 2. Set up Python (e.g., 3.10)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Build .app with PyInstaller
      #    We explicitly point to ai_platform_trainer/main.py
      - name: Build ai_platform_tainer.app
        run: |
          pip install pyinstaller
          pyinstaller ai_platform_trainer/main.py --windowed --name ai_platform_trainer
          # This creates dist/ai_platform_trainer.app

      # 5. Create a .dmg from the .app
      - name: Create DMG
        run: |
          hdiutil create ai_platform_trainer.dmg -volname ai_platform_trainer \
            -srcfolder dist/ai_platform_trainer.app \
            -ov -format UDZO

      # 6. Upload the .dmg so you can download it from the Actions UI
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4  # Note: use @v4 or latest
        with:
          name: AI Platform Trainer macOS
          path: ai_platform_trainer.dmg